// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceProgramMissionTracker;

namespace SpaceProgramMissionTracker.Migrations
{
    [DbContext(typeof(SiteContext))]
    [Migration("20190726150218_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpaceProgramMissionTracker.Model.Agency", b =>
                {
                    b.Property<int>("AgencyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("AgencyId");

                    b.ToTable("Agencies");

                    b.HasData(
                        new { AgencyId = 1, Name = "NASA" },
                        new { AgencyId = 2, Name = "Roscosmos" },
                        new { AgencyId = 3, Name = "ESA" },
                        new { AgencyId = 4, Name = "SpaceX" }
                    );
                });

            modelBuilder.Entity("SpaceProgramMissionTracker.Model.AgencyStellarBody", b =>
                {
                    b.Property<int>("AgencyStellarBodyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgencyId");

                    b.Property<int>("StellarBodyId");

                    b.HasKey("AgencyStellarBodyId");

                    b.HasIndex("AgencyId");

                    b.HasIndex("StellarBodyId");

                    b.ToTable("AgencyStellarBodies");

                    b.HasData(
                        new { AgencyStellarBodyId = 1, AgencyId = 1, StellarBodyId = 1 },
                        new { AgencyStellarBodyId = 2, AgencyId = 2, StellarBodyId = 2 },
                        new { AgencyStellarBodyId = 3, AgencyId = 3, StellarBodyId = 3 },
                        new { AgencyStellarBodyId = 4, AgencyId = 4, StellarBodyId = 4 }
                    );
                });

            modelBuilder.Entity("SpaceProgramMissionTracker.Model.Mission", b =>
                {
                    b.Property<int>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgencyId");

                    b.Property<string>("Name");

                    b.HasKey("MissionId");

                    b.HasIndex("AgencyId");

                    b.ToTable("Missions");

                    b.HasData(
                        new { MissionId = 1, AgencyId = 1, Name = "Apollo" },
                        new { MissionId = 2, AgencyId = 2, Name = "Venera" },
                        new { MissionId = 3, AgencyId = 3, Name = "Philae" },
                        new { MissionId = 4, AgencyId = 4, Name = "ISS Resupply" }
                    );
                });

            modelBuilder.Entity("SpaceProgramMissionTracker.Model.StellarBody", b =>
                {
                    b.Property<int>("StellarBodyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("StellarBodyId");

                    b.ToTable("StellarBodies");

                    b.HasData(
                        new { StellarBodyId = 1, Name = "Moon" },
                        new { StellarBodyId = 2, Name = "Venus" },
                        new { StellarBodyId = 3, Name = "Comet" },
                        new { StellarBodyId = 4, Name = "LEO" }
                    );
                });

            modelBuilder.Entity("SpaceProgramMissionTracker.Model.AgencyStellarBody", b =>
                {
                    b.HasOne("SpaceProgramMissionTracker.Model.Agency", "Agency")
                        .WithMany("AgencyStellarBodyList")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SpaceProgramMissionTracker.Model.StellarBody", "StellarBody")
                        .WithMany("AgencyStellarBodyList")
                        .HasForeignKey("StellarBodyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SpaceProgramMissionTracker.Model.Mission", b =>
                {
                    b.HasOne("SpaceProgramMissionTracker.Model.Agency")
                        .WithMany("Missions")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
